### ISSUE TITLE
ČDK - informace o původu dokumentu

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/ceska-digitalni-knihovna#10]
Informace v metadatech o tom, ze které knihovny dokument pochází se objevuje jenom při prohlížení první stránky. Po kliknutí na další stránku zmizí. Měla by tam být pořád.

**Comment by tumovam** [comment]
V modrém klientovi i UNNK (bílý klient) již funguje. V KNAV jsme během testování UNNK nad daty ČDK narazili na jiný problém s informacemi o původu dokumentu... 

V UNNK/ČDK není Místo uložení hypertextové ![obrazek](https://user-images.githubusercontent.com/31240271/58177102-0280ff80-7ca4-11e9-99ee-e13a6e6b650e.png), takže se uživatel nemůže prokliknout do knihovny, která dokument vlastní. Chyba není v metadatech, protože místo uložení je v MODSu v elementu location. 

V ostré instalaci UNNK (ne ČDK, ale [Kramerius KNAV](https://kramerius.lib.cas.cz/)) se po kliknutí na "Knihovna AV ČR" ![obrazek](https://user-images.githubusercontent.com/31240271/58176971-bdf56400-7ca3-11e9-9528-01da3a2d9869.png) stane filtr ![obrazek](https://user-images.githubusercontent.com/31240271/58177021-d4032480-7ca3-11e9-834f-f1bd2f609c3f.png), který následně zobrazí všechny dokumenty, jejichž vlastníkem je KNAV.  

V ČDK bychom chtěli, aby po kliknutí na název knihovny (Místo uložení) dostali do knihovny, která dokument vlastní a kdy se užvatel po kliknutí na název knihovny v sekci Původ titulu dostane přímo na konkrétní dokument. Ve stávajícím (modrém) klientovi je to možné zde: ![obrazek](https://user-images.githubusercontent.com/31240271/58177185-2fcdad80-7ca4-11e9-8e1d-986d43c6bb06.png). Tuto funkcionalitu bychom chtěli zachovat i v novém (bílém) klientovi. Děkuji

**Comment by zabak** [comment]
Cituji z vyřešeného issue výše: 

> Hotovo, např. http://kramerius.rychtar.cloud/cdk/uuid/uuid:da26d1bb-fc24-11e9-b79b-001b63bd97ba
> V konfiguraci je potřeba nastavit
> originLink: true v definici Krameria v krameriusList

@honza-rychtar  funguje toto nastavení stále? V konfiguraci klienta ČDK ho nevidím

**Comment by zabak** [comment]
Považuji za vyřešené. Pokud je potřeba nějak vylepšit, prosím o založení nového issue.
