### ISSUE TITLE
ČDK - indexování nových dokumentů z již existujících knihoven

### ISSUE THREAD

**Issue by pavelkocourek** [ceskaexpedice/ceska-digitalni-knihovna#13]
Jak teď probíhá doplnění nových dokumentů do čdk z knihoven, které již byly sklizené? KNAV i MZK mají nové dokumenty, které nebyly do ČDK přidány.
Zadávala jsem podobný dotaz v #325

**Comment by pavel-stastny** [comment]
Rizeno indexem.  Pokud se objevi v indexu nova titul, bude k dispozici ke sklizeni pro CDK
