### ISSUE TITLE
CDK klient - globalni ikona pro PDF neviditelna

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/ceska-digitalni-knihovna#14]
Zdravim,

na serveru CDK se u importovanych clanku v pdf nezobrazovala/nezobrazuje univerzalni ikona u nahledu. Doimportoval jsem do Fedory prislusny digitalni objekt s pid "icon:application_pdf" a nyni je v "klasickem" rozhrani u nahledu clanku jiz ikona zobrazovana. Nicmene v rozhrani klienta nikoliv. Bude tedy asi potreba jeste upravit/opravit zobrazeni v CDK klientovi.

Linky:

"klasika"
http://cdk.lib.cas.cz/search/i.jsp?pid=uuid:46321917-5647-11e1-86bc-005056a60003&q=#periodical-periodicalvolume-periodicalitem-article_uuid:8f453ab0-ca3c-86b3-898e-c58740647946

![search_01](https://cloud.githubusercontent.com/assets/8750622/18244784/35fe356a-7362-11e6-8742-f5db58f6c553.png)

"klient"
http://cdk.lib.cas.cz/client/index.vm?q=&page=doc&start=&rows=#pid=uuid:8f453ab0-ca3c-86b3-898e-c58740647946;hist=7;pmodel=periodicalitem

![client_01](https://cloud.githubusercontent.com/assets/8750622/18244798/4167b03e-7362-11e6-8b26-02218b368d05.png)

Diky, Duda

**Comment by zabak** [comment]
V novém klientu funguje, zavírám
