### ISSUE TITLE
ČDK - procházení podle zapojených knihoven (místa uložení)

### ISSUE THREAD

**Issue by tumovam** [ceskaexpedice/ceska-digitalni-knihovna#23]
V KNAV testujeme UNNK (bílý klient) nad daty ČDK... 
V modrém klientovi se jednalo o Sbírky, nyní Procházení přes Místo uložení (zatím máme pojmenované jako Knihovny). 
V ČDK nyní máme data od 10 knihoven. Pokud si vpravo nahoře zvolím řazení Podle výskytů, zobrazí se seznam 10 zapojených knihoven:
![obrazek](https://user-images.githubusercontent.com/31240271/58179122-d1a2c980-7ca7-11e9-8b4d-f363b50f354d.png)

Když ale vyberu možnost řazení Abecedně, objeví se pouze 4:
![obrazek](https://user-images.githubusercontent.com/31240271/58179157-eaab7a80-7ca7-11e9-8870-c75f39440395.png)

Jedná se o bug, nebo máme někde něco špatně nastavené? Děkuji

**Comment by honza-rychtar** [comment]
Souvisí to s více věcmi. 
V ČDK je ohnuta logika sbírek a sbírky slouží jako rozlišení knihovny.
V indexu jsou ale pořád identifikátory sbírek z jednotlivých knihoven a je jich celkem přes 100.
Sbírek je v Krameriovi ČDK však jen 10.
Identifikátory se pak mapují na názvy. Pokud je seřadím podle abecedy, tak mi některé sbírky reprezentující knihovny skočí až za stou pozici. No a tady přichází druhý problém, že stránkování u procházení funguje správně až od Krameria verze 5.3.9, takže za stou pozici už se v klientovi nedostanu.

To řazení podle abecedy na úrovni solr dotazu nemá smysl - sbírky se znovu seřadí až po namapování názvů. Takže jsem to teď v klientovi **opravil** tak, že dotaz do solru je vždy řazený podle výskytů.
To teď bude fungovat, ale neřeší to všechny probémy.

Závěr.
* ČDK by bylo dobré aktualizovat - u procházení nefunguje stránkování, i u autorů je jen 100 výsledků http://www.digitalniknihovna.cz/cdk/browse?sort=occurrence&category=authors
* V ČDK jsou sbírky nekonzistentní - na úrovni seznamu sbírek se tváří, že jich je jen 10. Ale v indexu jsou i původní sbírky.

**Comment by zabak** [comment]
Funguje, zavírám
