### ISSUE TITLE
Sloučení kramerius.mzk.cz a krameriusndktest.mzk.cz

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/ceska-digitalni-knihovna#3]
Došlo ke sloučení kramerius.mzk.cz a krameriusndktest.mzk.cz, všechny dokumenty jsou nyní dostupné na kramerius.mzk.cz. Bude potřeba buď změnit odkazy na obrázky ve sklizených datech nebo sklidit znovu.

**Comment by pavel-stastny** [comment]
@zabak Jiz neni aktualni, zaviram.
