### ISSUE TITLE
Procházení - neexistující  browse.category.access

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/ceska-digitalni-knihovna#40]
V ČDK klientovi je jako default kategorie pro procházení browse.category.access, která nemá v žádném jazyce překlad a nefunguje (točí se kolečko). @honza-rychtar  můžeš se na to podívat?

**Comment by honza-rychtar** [comment]
@zabak v nové verzi opraveno.

**Comment by pavel-stastny** [comment]
@zabak @honza-rychtar Již neaktuální
