### ISSUE TITLE
Přejmenovat SVKUL

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/ceska-digitalni-knihovna#41]
Prosím změnit název Severočeská vědecká knihovna v Ústí nad Labem na Knihovna Ústeckého kraje. Je to přinejmenším ve fasetě Zdroj a Místo uložení. Logo se zatím nemění.

**Comment by zabak** [comment]
Anglická verze je Ústí Regional Library

**Comment by pavel-stastny** [comment]
V klientovi již přejmenováno.
