### ISSUE TITLE
Vyhledávání textu s mezerou v uvozovkách končí chybou v K 5.8

### ISSUE THREAD

**Issue by klodner** [ceskaexpedice/ceska-digitalni-knihovna#44]
"Jiří Němec" (s uvozovkami)

Kramerius 5.8.3 - chyba
https://kramerius.vse.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=%22Ji%C5%99%C3%AD+N%C4%9Bmec%22&issn=&title=&keywords=&author=&rok=&udc=&ddc=&shelfLocator=&physicalLocation=

Kramerius 5.7.2 (a starší verze) fungue

https://kramerius.nacr.cz/search/r.jsp?forProfile=search&forProfile_sorting_dir=&debug=&sort=&q=%22Ji%C5%99%C3%AD+N%C4%9Bmec%22&issn=&title=&keywords=&author=&rok=&udc=&ddc=&shelfLocator=&physicalLocation=

Nový klient také funguje

**Comment by pavel-stastny** [comment]
Přesunoto do issues jádra [956](https://github.com/ceskaexpedice/kramerius/issues/956)
