### ISSUE TITLE
chybně naimportovaný svazek - zdvojené stránky

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/ceska-digitalni-knihovna#5]
Ten sborník z elagu co jsme dnes testovali (14th Library systems seminar Brussels) je chybně naimportovaný - zdvojily se všechny stránky, každá je 1x volně dostupná a 1x nedostupná. V NTK je to správně. http://cdk.lib.cas.cz/client/index.vm?q=14th+Library+systems+seminar+Brussels&page=doc&start=0&rows=#pid=uuid:a6ce9055-632d-11e3-9840-001b63bd97ba

**Comment by pavel-stastny** [comment]
@zabak Zdvojeni je nyni reseno na urovni zobrazeni titulu
