### ISSUE TITLE
Nemožnost přihlášení do ČDK

### ISSUE THREAD

**Issue by jandera** [ceskaexpedice/ceska-digitalni-knihovna#50]
Hlásí mi to, že můj e-mail už existuje a při pokusech to jakkoli prostřelit, s informací o odeslání e-mailu, mi nic nepřichází a přihlásit se nemohu. Ukázka zde: https://drive.google.com/file/d/1O98cNNCQcLd-KS3sP65soy4yeHE9A_yd/view?usp=sharing

**Comment by pavel-stastny** [comment]
@jandera Již řeší kolegové z MZK.

**Comment by pavel-stastny** [comment]
@jandera Již by mělo fungovat.  Poprosil bych o vyzkoušení.

**Comment by jandera** [comment]
Ano, potvrzuji, přihlášení již funguje. Ale při přístupu k DNNT-O je v modrém pruhu nahoře místo eduPersonPrincipalName mail nebo authMail.

**Comment by zabak** [comment]
@pavel-stastny tento problém zdá se přetrvává. Opravíš to ty?

**Comment by pavel-stastny** [comment]
@zabak Vypadá to, že to bylo endpoitem `~/user `ve větvi čdk.  Udělal jsem komit až bude argo tak provedu redeploy.

**Comment by jandera** [comment]
@pavel-stastny @zabak  momentálně nemohu ověřit, zda je už je u DNNT v pruhu eduPersonPrincipalName nebo něco jiného, v ČDK se mi ani po opakovaném přihlášení nezobrazí strana DNNT dokumentu.
V DK MZK (www.digitalniknihovna.cz/mzk) se mi pokusné dokumenty zobrazují, ale zas je tam v pruhu atribut eduPersonUniqueId a v DK KNAV i NDK je zas eduPersonPrincipalName.

**Comment by pavel-stastny** [comment]
@jandera Podivam se na to.

**Comment by jandera** [comment]
@pavel-stastny Problém stále přetrvává, do ČDK se sice přihlásím, ale na DNNT dílo se nedostanu, zatímco v NDK i DK MZK ano a stále platí že v DK MZK ([www.digitalniknihovna.cz/mzk](http://www.digitalniknihovna.cz/mzk)) se mi dokumenty zobrazují, ale je tam v pruhu atribut eduPersonUniqueId a v DK KNAV i NDK je zas eduPersonPrincipalName.
To že se mi dokument v ČDK nezobrazí je zřejmě to samé o čem je #34 např.:
https://ndk.cz/uuid/uuid:b341ab7c166c607c644cb01ea0cf5170
https://www.digitalniknihovna.cz/mzk/uuid/uuid:10aa018e-af79-cbd1-27f6-a03b7dd0482e
http://cdk.kramerius.org/uuid/uuid:b341ab7c166c607c644cb01ea0cf5170

Btw je zvláštní, že i když odkazuji do všech Kramerií na stejný dokument a stejnou stránku v DK MZK je v url jiné UUID než u NDK a ČDK.

**Comment by pavel-stastny** [comment]
@jandera @kerschfilip KNAV a SVKHK dokumenty by už měly být dostupné,

**Comment by pavel-stastny** [comment]
@jandera Nakonec po kozultaci s @zabak to vypadá, že správná hodnota je **eduPersonUniqueId**. Tento atribut je přímo dostupný z K7 instancí ale, bohužel, už ne z K5 instancí.  Muselo by se měnit mapovaní v shibrules.txt a pak by se musela udělat i změna ve web klientovi (který v případě k5 zobrazuje atribut **session_eppn**).  Přidávam do diskuze  @honza-rychtar  a 
@mduda100871

**Comment by mduda100871** [comment]
Čistě za sebe už bych neřešil, ztráta času, který se nám nedostává jinde.

MD

**Comment by jandera** [comment]
@mduda100871 @pavel-stastny @zabak Ok, tak to tak nechme, stejně za chvilku snad všichni budeme mít K7. Zavírám.
