### ISSUE TITLE
Doplnit textový název pro nkp

### ISSUE THREAD

**Issue by zabak** [ceskaexpedice/ceska-digitalni-knihovna#52]
Udělat to tak, aby se ten název buď přebíral z registru Krameriů nebo z admin rozhraní.

**Comment by honza-rychtar** [comment]
Teď to má klient ve svých lokalizačních souborech.
https://github.com/ceskaexpedice/kramerius-web-client/blob/140e9eee603e2dc4a71bdfb4bc6ff16dd42a43fe/src/assets/i18n/cs.json#L785

```
 "source": {
    "mzk": "Moravská zemská knihovna",
    "svkhk": "Studijní a vědecká knihovna v Hradci Králové",
    "knav": "Knihovna Akademie věd ČR",
    "uzei": "Knihovna Antonína Švehly",
    "svkul": "Knihovna Ústeckého kraje",
    "kkp": "Krajská knihovna v Pardubicích",
    "nfa": "Knihovna Národního filmového archivu"
  },
```

Teď bude určitě nejjednodušší to přidat sem. 
Potom to můžeme napojit na Registr.

**Comment by zabak** [comment]
Díky - funguje
