### ISSUE TITLE
Nedostupne dokumenty

### ISSUE THREAD

**Issue by pavel-stastny** [ceskaexpedice/ceska-digitalni-knihovna#7]
Nektere dokumenty na CDK zobrazi zpravu o nedostupnosti pritom na zdrojovem K5 jsou verejne dostupne.

**Comment by slapakovai** [comment]
konkrétní příklad: http://cdk.lib.cas.cz/client/handle/uuid:1e4b4d64-4048-11e1-1729-001143e3f55c
